name: CI

on:
  push:

env:
  PNPM_VERSION: 9.6.0

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run test
        env:
          TZ: UTC
        run: pnpm test
