name: Dispatch update
on:
  push:
    branches:
      - develop

env:
  APP_ID: ${{ secrets.APP_ID }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Apps token
        uses: tibdex/github-app-token@v2
        id: create_token
        with:
          app_id: ${{ env.APP_ID }}
          private_key: ${{ env.PRIVATE_KEY }}
      - run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.create_token.outputs.token }}" "https://api.github.com/repos/taga3s/Rhythmate-Web/dispatches" -d '{ "event_type": "update" }'
